name: Go CI/CD

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Run go mod tidy
        run: go mod tidy

      - name: Build service
        run: go build -o service

      - name: Build repository
        run: go build -o repository

      - name: Build cmd
        run: go build -o cmd

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: executables
          path: |
            cmd/teamdev.exe

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Run tests
        run: go test ./tests/...

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: executables
          path: ./

      - name: Create Release
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.sha }}
          files: |
            teamdev.exe
          tag_name: v0.1.${{ github.run_number }}
          generate_release_notes: true