name: Go CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Run go mod tidy
      run: go mod tidy

    - name: Build service
      run: go build -o service

    - name: Build repository
      run: go build -o repository

    - name: Build cmd
      run: go build -o cmd

    - name: Run tests repo_mocks
      run: go test -v ./tests/repository_mocks
    
    - name: Run tests services
      run: go test -v ./tests/test_services
    